# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.9.3
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /home/gaby/dev-env/dockers/examples/podman/httpd/htdocs:z
  creationTimestamp: "2025-05-20T08:10:52Z"
  labels:
    app: mypod
  name: mypod
spec:
  containers:
  - image: localhost/myimage:latest
    name: myapp
    ports:
    - containerPort: 80
      hostPort: 8080
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs
      name: home-gaby-dev-env-dockers-examples-podman-httpd-htdocs-host-0
  volumes:
  - hostPath:
      path: /home/gaby/dev-env/dockers/examples/podman/httpd/htdocs
      type: Directory
    name: home-gaby-dev-env-dockers-examples-podman-httpd-htdocs-host-0
