version: '2'
services:
    nginx:
        image: nginx
        volumes:
#            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./conf.d:/etc/nginx/conf.d/:ro
        ports:
            - 8080:80
