apiVersion: v1
kind: Service
metadata:
    name: hello-blue-whale-svc
spec:
    type: NodePort
    selector:
        app: hello-blue-whale-app
    ports:
       -  port: 80
          targetPort: 80
          nodePort: 30010
        
