apiVersion: v1
kind: Service
metadata:
    name: dictionary-server-service
spec:
    type: LoadBalancer
    selector:
        app: dictionary-server
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
