version: '2'
services:
    wordpress:
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
    db:
        environment:
            MARIADB_DATABASE: wordpress
            MARIADB_USER: wordpress
            MARIADB_PASSWORD: wordpress
            MARIADB_ROOT_PASSWORD: example

networks:
    backend:
        driver: overlay
    frontend:
        driver: overlay
