version: '2'
services:
  testservice:
    build:
      context: "/home/gaby/private/dockers/examples"
      dockerfile: "Dockerfile.volumes"
    volumes:
     - /home/gaby/private/shared:/data
    ports :
    - 8080:8080