# complete-example.yaml
apiVersion: openfaas.com/v1
kind: Function
metadata:
    name: nodeinfo
    namespace: openfaas-fn
spec:
    name: nodeinfo
    handler: node main.js
    image: functions/nodeinfo:latest
    labels:
        com.openfaas.scale.min: "2"
        com.openfaas.scale.max: "5"
    environment:
        write_debug: "true"
    limits:
        cpu: "200m"
        memory: "256Mi"
    requests:
        cpu: "10m"
        memory: "128Mi"
    constraints:
        - "cloud.google.com/gke-nodepool=default-pool"
    secrets:
        - nodeinfo-secret1
        
