version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  fn1:
    lang: go
    handler: ./fn1
    image: fn1:latest

  fn2:
    lang: go
    handler: ./fn2
    image: fn2:latest

