version: "3.5"
services:
    web:
        image: fundamentalsofdocker/ch08-web:1.0
        networks:
            - pets-net
        ports:
            - 3000:3000
        deploy:
            replicas: 3
    db:
        image: fundamentalsofdocker/ch08-db:1.0
        networks:
            - pets-net
        volumes:
            - pets-data:/var/lib/postgresql/data
volumes:
    pets-data:
networks:
    pets-net:
        driver: overlay