apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    book: microservices4javadev
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
  selector:
    app: api-gateway
